os: linux
language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=^2.8.0

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=^2.3.0
    - php: 7.1
      env: SYMFONY_VERSION=^2.7.0
    - php: 7.1
      env: SYMFONY_VERSION=^2.8.0
    - php: 7.1
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      env: SYMFONY_VERSION=^4.0
    - php: 7.3
      env: SYMFONY_VERSION=^4.0
    - php: 7.4
      env: SYMFONY_VERSION=^4.0
      dist: bionic
    - php: 7.2
      env: SYMFONY_VERSION=^5.0
    - php: 7.3
      env: SYMFONY_VERSION=^5.0
    - php: 7.4
      env: SYMFONY_VERSION=^5.0
      dist: bionic

before_script:
  - phpenv config-rm xdebug.ini

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: COMPOSER_MEMORY_LIMIT=-1 composer install

script:
  - vendor/bin/simple-phpunit
